### PR TITLE
Branch fix bugs

### PR DESCRIPTION
**Pull request by Mohammed-Faizzzz**
Previous Merge failed CI Checks due to issues such as `no newline at EOF`. This PR rectifies those issues.

### CODE REVIEW

**Comment by Mohammed-Faizzzz** [comment]
Currently, checks fail due to failing testcases. I think we should go ahead and merge this so we can continue on our work for v1.2, then rewrite our testcases according to v1.2

**Comment by Mohammed-Faizzzz** [comment]
I have fixed previously failing testcases in AddCommandParserTest. Although new mandatory fields "NRIC" and "Gender" were introduced, the tests in AddCommandParserTest (and other related classes such as PersonBuilder) were not modified to accomodate the new changes. Although bugs have been fixed, we still have to include new tests to test the new changes (such as testing for invalid gender input, etc.)

**Review by tanveersingh10 — APPROVED** [review]
looks great couldn't find any nits

**Review by cmHuang777 — APPROVED** [review]
Thanks for fixing the tests. I think we can merge first and bring up the cover coverage later on.

**Pull request merged**
