### PR TITLE
Add Typical Addressbook and update DG

### PR DESCRIPTION
**Pull request by tanveersingh10**

### CODE REVIEW

**Review by Mohammed-Faizzzz — APPROVED** [review]
Looks Good, Tanveer! I noticed you replaced `AddressBookBuilder` with `TypicalAddressBook` in several classes. Can you clarify the reasoning? What is the improvement that this change brings?

**Comment by tanveersingh10** [comment]
> Looks Good, Tanveer! I noticed you replaced `AddressBookBu`

**Comment by tanveersingh10** [comment]
> > Looks Good, Tanveer! I noticed you replaced `AddressBookBu`

Just wanted to follow a similar abstraction as Typical Doctor and Typical Patient. I think it makes more sense with the structure of the project

**Review by cmHuang777 — APPROVED** [review]
LGTM, thanks for improving code quality

**Pull request merged**
